import tkinter as tk
window = tk.Tk ()

f = tk.Frame (bg = "light gray")
f.pack ()

lblone = tk.Label (master = f, text = "- American Foods - ", bg = "dark red", fg = "gold", width = 32, font = ("Cambria", 23))
lblone.pack()
lbltwo = tk.Label (master = f, font = ("Cambria", 11), bg = "light gray", text = "\nSearch in this area to find proudly American foods and interesting facts about\nthem. This is not an area to purchase foods, much less a restaurant website.\n")
lbltwo.pack()

burger = tk.PhotoImage (file = "American Food.png")
a = tk.Label (master = window, image = burger)
a.pack (side = tk.TOP)

ftwo = tk.Frame (bg = "light gray")
ftwo.pack ()

lblthree = tk.Label (master = ftwo, bg = "light gray", font = ("Cambria", 11), height = 1, width = 68, text = ("\n- Foods -\n"))
lblthree.pack ()

butone = tk.Button (master = ftwo, bg = "gray", fg = "black", width = 38, text = "Cheeseburger")
butone.pack(side = tk.LEFT)
def displayOne (event):
    fcb = tk.Frame (bg = "light gray")
    fcb.pack ()
    lblcbone = tk.Label (master = fcb, height = 1, font = ("Cambria", 15), fg = "gold", bg = "dark red", width = 50, text = "- Cheeseburger -")
    lblcbone.pack ()
    lblcbtwo = tk.Label (master = fcb, height = 7, font = ("Cambria", 10), fg = "black", bg = "light gray", width = 60, text = "Cheeseburgers are possibly the most uniquely American food of all. They\ncontain a beef patty (usually a quarter pound) and have chesse melted on\ntop. Cheeseburgers also usually have lettuce, tomato, onions, and sauces\nincluding ketchup and sometimes even mustard. Cheeseburgers are usually\ngrilled, and are mass produced in several fast food companines today,\nthough none of them are as good as a standard, homemade cheeseburger.")
    lblcbtwo.pack ()
    butcb = tk.Button (master = fcb, width = 77, bg = "gray", fg = "black", text = "Close Information")
    butcb.pack()
    def displayCb (event):
        lblcbone.pack_forget ()
        lblcbtwo.pack_forget ()
        butcb.pack_forget ()
        fcb.pack_forget ()
    butcb.bind ("<Button-1>", displayCb)
buttwo = tk.Button (master = ftwo, bg = "gray", fg = "black", width = 38, text = "Fries")
buttwo.pack(side = tk.RIGHT)
def displayTwo (event):
    ffr = tk.Frame (bg = "light gray")
    ffr.pack ()
    lblfrone = tk.Label (master = ffr, height = 1, font = ("Cambria", 15), fg = "gold", bg = "dark red", width = 50, text = "- Fries -")
    lblfrone.pack ()
    lblfrtwo = tk.Label (master = ffr, height = 7, font = ("Cambria", 10), fg = "black", bg = "light gray", width = 60, text = "Fries or 'French Fries' are found widespread throughout the United States\nand accompany dense American foods inlcuding burgers and fried chicken.\nFries are made of plain potatoes, though some special fries are made from\nsweet potatoes creating a more sugary taste. Fries are very common to\nfind in fast food restuarants, and are usually dipped in ketchup and in\nseveral other sauces. Fries are usually deep fried, but can be cooked.")
    lblfrtwo.pack ()
    butfr = tk.Button (master = ffr, width = 77, bg = "gray", fg = "black", text = "Close Information")
    butfr.pack ()
    def displayFr (event):
        lblfrone.pack_forget ()
        lblfrtwo.pack_forget ()
        butfr.pack_forget ()
        ffr.pack_forget ()
    butfr.bind ("<Button-1>", displayFr)
fthree = tk.Frame (bg = "light gray")
fthree.pack ()
butthree = tk.Button (master = fthree, bg = "gray", fg = "black", text = "Mac & Cheese", width = 38)
butthree.pack(side = tk.LEFT)
def displayThree (event):
    fmc = tk.Frame (bg = "light gray")
    fmc.pack ()
    lblmcone = tk.Label (master = fmc, height = 1, font = ("Cambria", 15), fg = "gold", bg = "dark red", width = 50, text = "- Mac & Cheese -")
    lblmcone.pack ()
    lblmctwo = tk.Label (master = fmc, height = 7, font = ("Cambria", 10), fg = "black", bg = "light gray", width = 60, text = "Mac & Cheese is very common throughout the US, and come in several\ndifferent forms. At its best form, Mac & Cheese is melted on top of macroni\n and put in the oven along with toppings like bacon bits. However, sometimes\npeople make this dish from a box, and don't put it in the oven, and\nhave other toppings. American Cheese is the best type of cheese for using,\nbut some other people use cheddar cheese or even swiss cheese instead.")
    lblmctwo.pack ()
    butmc = tk.Button (master = fmc, width = 77, bg = "gray", fg = "black", text = "Close Information")
    butmc.pack ()
    def displayMc (event):
        lblmcone.pack_forget ()
        lblmctwo.pack_forget ()
        butmc.pack_forget ()
        fmc.pack_forget ()
    butmc.bind ("<Button-1>", displayMc)
ffour = tk.Frame (bg = "light gray")
ffour.pack ()
butfour = tk.Button (master = fthree, bg = "gray", fg = "black", text = "Baked Beans", width = 38)
butfour.pack(side = tk.RIGHT)
def displayFour (event):
    fbb = tk.Frame (bg = "light gray")
    fbb.pack ()
    lblbbone = tk.Label (master = fbb, height = 1, font = ("Cambria", 15), fg = "gold", bg = "dark red", width = 50, text = "- Baked Beans -")
    lblbbone.pack ()
    lblbbtwo = tk.Label (master = fbb, height = 7, font = ("Cambria", 10), fg = "black", bg = "light gray", width = 60, text = "Baked Beans are made from a variety of beans, though they all are\ncoated in a sugary bean sauce. Beans are very common in sections all around\nthe United States, particularly in the Southeast and the Southwest. There are\nbrands today that make bake beans in cans, but these beans can\nbe made at home. Some people make crispy baked beans, though it can take away\nthe sugar sauce that coats the beans which makes the beans fairly dry.")
    lblbbtwo.pack ()
    butbb = tk.Button (master = fbb, width = 77, bg = "gray", fg = "black", text = "Close Information")
    butbb.pack ()
    def displayBb (event):
        lblbbone.pack_forget ()
        lblbbtwo.pack_forget ()
        butbb.pack_forget ()
        fbb.pack_forget ()
    butbb.bind ("<Button-1>", displayBb)
ffive = tk.Frame (bg = "light gray")
ffive.pack ()
butfive = tk.Button (master = ffour, bg = "gray", fg = "black", text = "Potato Chips", width = 38)
butfive.pack(side = tk.LEFT)
def displayFive (event):
    fpc = tk.Frame (bg = "light gray")
    fpc.pack ()
    lblpcone = tk.Label (master = fpc, height = 1, font = ("Cambria", 15), fg = "gold", bg = "dark red", width = 50, text = "- Potato Chips -")
    lblpcone.pack ()
    lblpctwo = tk.Label (master = fpc, height = 7, font = ("Cambria", 10), fg = "black", bg = "light gray", width = 60, text = "Potato Chips are made from potatoes (obviously) and can usually accompany\nsandwiches, though can really accompany anything. These chips are\nsalty and usually have and indented pattern running across the chip. Some\npeople make their chips out of other materials besides plain potato,\nincluding sweet potato chips, but they usually aren't as good. Potato Chips\ncan be made at home, though potato chips are mostly bought at the store.")
    lblpctwo.pack ()
    butpc = tk.Button (master = fpc, width = 77, bg = "gray", fg = "black", text = "Close Information")
    butpc.pack ()
    def displayPc (event):
        lblpcone.pack_forget ()
        lblpctwo.pack_forget ()
        butpc.pack_forget ()
        fpc.pack_forget ()
    butpc.bind ("<Button-1>", displayPc)
fsix = tk.Frame (bg = "light gray")
fsix.pack ()
butsix = tk.Button (master = ffour, bg = "gray", fg = "black", text = "Corn on the Cob", width = 38)
butsix.pack(side = tk.RIGHT)
def displaySix (event):
    fcc = tk.Frame (bg = "light gray")
    fcc.pack ()
    lblccone = tk.Label (master = fcc, height = 1, font = ("Cambria", 15), fg = "gold", bg = "dark red", width = 50, text = "- Corn on the Cob -")
    lblccone.pack ()
    lblcctwo = tk.Label (master = fcc, height = 7, font = ("Cambria", 10), fg = "black", bg = "light gray", width = 60, text = "Corn on the Cob is basically corn still attached to its central spine.\nCorn on the cob is usually grilled, though sometimes people cook it\nin the oven to prevent scorch marks from the grill. Corn on the cob is\nvery special in the United States, because corn is a uniquely American\nthing. Unlike plain corn, corn on the cob is has its kernels still attached to\nits spine when eaten. Corn on the cob isn't fast food and is 100% natural.")
    lblcctwo.pack ()
    butcc = tk.Button (master = fcc, width = 77, bg = "gray", fg = "black", text = "Close Information")
    butcc.pack ()
    def displayCc (event):
        lblccone.pack_forget ()
        lblcctwo.pack_forget ()
        butcc.pack_forget ()
        fcc.pack_forget ()
    butcc.bind ("<Button-1>", displayCc)
butone.bind ("<Button-1>", displayOne)
buttwo.bind ("<Button-1>", displayTwo)
butthree.bind ("<Button-1>", displayThree)
butfour.bind ("<Button-1>", displayFour)
butfive.bind ("<Button-1>", displayFive)
butsix.bind ("<Button-1>", displaySix)

window.mainloop ()